### ISSUE TITLE
Connect bridge between Dapps and Wallet

### ISSUE THREAD

**Issue by astha-nimblechapps** [WalletConnect/node-walletconnect-bridge#18]
Hi

This plugin for bridge how to implement it in react and react-native application to make a communication between client sdk with bridge (dapps and wallet). Can you provide the whole example for Bridge and client sdk connection (dapps and wallet). Dont know what's happing in dapps.

Thanks in Advance.
Appreciate it

**Comment by pedrouid** [comment]
Need to improve the documentation but it should give you a rough picture

https://docs.walletconnect.org/tech-spec#establishing-connection

The bridge is the WebSocket Server relaying the messages between the two parties. It guarantees the message delivery by caching the subscriptions of each end.

Both the dapp and the wallet send a `Sub` payload for their own clientId topic then whenever they want to send a message to each other they send a `Pub` payload and the bridge will serve to the corresponding socket with a subscription matching that topic.

You can read more about the WebSocket messages here:
https://docs.walletconnect.org/tech-spec#websocket-messages
