### ISSUE TITLE
Purpose of /subscribe endpoint

### ISSUE THREAD

**Issue by jpopxfile** [WalletConnect/node-walletconnect-bridge#19]
Hi,

I have observed while using the sample [here](https://example.walletconnect.org) that this endpoint is not used. Also, even if a topic and webhook subscription is added, they are not used as pushNotification https://github.com/WalletConnect/node-walletconnect-bridge/blob/5c9bc1e553cda874848f3c1eb8a80f97b937d104/src/notification.ts#L11 is never called or used.

Running it locally, the app crashes when making a POST request as such

Request
```
curl -i -s -k  -X $'POST' \
    -H $'Host: 0.0.0.0:5001' -H $'Cache-Control: max-age=0' -H $'Upgrade-Insecure-Requests: 1' -H $'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36' -H $'DNT: 1' -H $'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H $'Accept-Encoding: gzip, deflate' -H $'Accept-Language: en,en-US;q=0.9' -H $'Connection: close' \
    $'http://0.0.0.0:5001/subscribe'
```

Log
```
INFO  [2019-04-01 07:23:58.693 +0000] (7642 on localhost.localdomain): incoming request
    reqId: 1
    req: {
      "method": "POST",
      "url": "/subscribe",
      "hostname": "0.0.0.0:5001",
      "remoteAddress": "127.0.0.1",
      "remotePort": 36572
    }
/home/raynold/Work/node-walletconnect-bridge/build/index.js:90
      topic = _req$body.topic,
                        ^

TypeError: Cannot read property 'topic' of null
```

I was wondering what the purpose of /subscribe endpoint is, and if it's possible to disable it if it is not in used.

**Comment by pedrouid** [comment]
The /subscribe endpoint is supposed to be used by native mobile applications to subscribe topics with webhook that will trigger push notifications.

I haven't heavily tested it but I want to understand a bit more of what's breaking the app. It looks it's missing the topic on the request body but I don't know how that would break the app, it should instead respond with a 400 status code. (check [L33](https://github.com/WalletConnect/node-walletconnect-bridge/blob/5c9bc1e553cda874848f3c1eb8a80f97b937d104/src/index.ts#L33))

Thanks for reporting it, I will look into it as well. Let me know if you find anything.

**Comment by jpopxfile** [comment]
It breaks at the line before because req.body is null.

**Comment by pedrouid** [comment]
I see, that's a simple fix then

**Comment by jpopxfile** [comment]
> The `/subscribe` endpoint is supposed to be used by native mobile applications to subscribe topics with webhook that will trigger push notifications.

How is this used currently? In the code, it seems like there is no usage of the subscribed notifications.

Also, since the webhook can be any user supplied value, would there be the risk of SSRF?

**Comment by pedrouid** [comment]
This is used on the React-Native, Kotlin and Swift libraries which are targetted at native mobile applications (mostly Wallets). They can use this endpoint to subscribe their push notifications, it's an option provided for improved UX but not at all required for the protocol. Perhaps this could be decoupled as a plugin.

However currently the protocol is designed in a way that the Dapp is the connection initiator and therefore decides which Bridge server to use. This could be improved perhaps with a new JSON-RPC request to switch Bridge servers.

I'm not familiar with SSRF, could you provide an attack vector example for this?

**Comment by jpopxfile** [comment]
> They can use this endpoint to subscribe their push notifications, it's an option provided for improved UX but not at all required for the protocol. Perhaps this could be decoupled as a plugin.

However, with this current implementation, even if the Dapp uses the /subscribe endpoint, it seems like the bridge server can only receive the subscriptions, and not push notifications.

As for SSRF, what can be done is quite limited since it is using POST. I checked and it appears that CRLF characters do not work for axios, so I am unable to make it convert the POST request into another request method

An arbitrary webhook such as http://127.0.0.1:[port] or some internal endpoint can be set as the webhook url. This can cause the server to make a request to an endpoint that the user will normally not be able to access.
